# Generated by Django 5.1.3 on 2024-11-27 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sceapp', '0003_remove_post_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
